import { CountryCode } from './Country';
import { Currency } from './Currency';
import { Address } from './OrderDetails';

export enum Genre {
  'Fantasy',
  'Science Fiction',
  'Dystopian',
  'Adventure',
  'Romance',
  'Detective & Mystery',
  'Horror',
  'Thriller',
  'LGBTQ+',
  'Historical Fiction',
  'Young Adult (YA) (13-17 yrs)',
  "Children's Fiction ",
  'Nonfiction Genres',
  'Memoir & Autobiography',
  'Biography',
  'Cooking',
  'Art & Photography',
  'Self-Help / Personal Development',
  'Motivational / Inspirational',
  'Health & Fitness',
  'History',
  'Crafts',
  'Hobbies & Home',
  'Families & Relationships',
  'Humor & Entertainment',
  'Business & Money',
  'Law & Criminology',
  'Politics & Social Sciences',
  'Religion & Spirituality',
  'Education & Teaching',
  'Travel',
  'True Crime',
}
